const axios = require("axios");

const SaveFile = require("./scripts/SaveFile");

async function main() {
  const PavelInnokentevichGalanin_Array = await getArrayJson(
    "https://Pavel-Innokentevich-Galanin.github.io/github-site-parser/Pavel-Innokentevich-Galanin.json"
  );
  const BrSTUPO4PavelGalanin_Array = await getArrayJson(
    "https://Pavel-Innokentevich-Galanin.github.io/github-site-parser/BrSTU-PO4-Pavel-Galanin.json"
  );
  const ooodepa_Array = await getArrayJson(
    "https://Pavel-Innokentevich-Galanin.github.io/github-site-parser/ooodepa.json"
  );
  const ToDoCalendar_Array = await getArrayJson(
    "https://Pavel-Innokentevich-Galanin.github.io/github-site-parser/ToDoCalendar.json"
  );

  const obj = {
    "Pavel-Innokentevich-Galanin": PavelInnokentevichGalanin_Array,
    "BrSTU-PO4-Pavel-Galanin": BrSTUPO4PavelGalanin_Array,
    ooodepa: ooodepa_Array,
    ToDoCalendar: ToDoCalendar_Array,
  };

  let str = `
# Pavel-Innokentevich-Galanin GitHub profile

- JSON generated by https://github.com/Pavel-Innokentevich-Galanin/github-site-parser
- MarkDown created by https://github.com/Pavel-Innokentevich-Galanin/Pavel-Innokentevich-Galanin/tree/main

`;

  const timeNow = new Date();
  Object.keys(obj).forEach((key) => {
    str += `\n## ${key}\n`;
    obj[key].forEach((repos, index) => {
      str += `
<details>
  <summary>
    <table>
      <tr>
        <td width="100">More</td>
        <td width="300">:file_folder: <b>${repos.name}</b></td>
        <td width="200">${
          repos.more.license.name !== ""
            ? `:green_book: ${repos.more.license.name}`
            : ""
        }</td>
        <td width="100">${
          repos.more.watchers !== 0 ? `:eyes: ${repos.more.watchers}` : ""
        }</td>
        <td width="100">${
          repos.more.stars !== 0 ? `:star: ${repos.more.stars}` : ""
        }</td>
        <td width="100">${
          repos.more.forks !== 0 ? `:electric_plug: ${repos.more.forks}` : ""
        }</td>
      </tr>
    </table>
  </summary>
  <ul>
    <li><b>Url</b>: ${repos.html_url}</li>
    <li><b>Owner</b>: <a href="https://github.com/${repos.owner.login}">${
        repos.owner.login
      }</a></li>
    <li><b>Updated at</b>: ${getStringDate(new Date(repos.updated_at))}</li>
    <li><b>Description</b>: ${repos.more.description}</li>
    <li><b>License</b>: ${
      repos.more.license.name !== ""
        ? `<a href="${repos.more.license.url}">${repos.more.license.name}</a>`
        : "none"
    }</li>
    <li><b>Stars</b>: :star: ${repos.more.stars}</li>
    <li><b>Watchers</b>: :eyes: ${repos.more.watchers}</li>
    <li><b>Forks</b>: :electric_plug: ${repos.more.forks}</li>
    <li><b>Languages</b>: <ul>${repos.languages
      .map((language_element) => {
        let procent = parseFloat(
          (language_element.counter * 100) / language_element.sum
        ).toFixed(2);
        procent = procent < 10 ? `0${procent}` : `${procent}`;
        return `
          <li>${procent} % - ${language_element.language}</li>`;
      })
      .join("")}</ul></li>
  </ul>
</details>
`;
    });
  });

  SaveFile("./build/README.md", str);
}

main();

async function getArrayJson(url) {
  try {
    const response = await axios.get(url);
    const data = response.data;
    return data;
  } catch (error) {
    console.log(error);
    return [];
  }
}

function getStringDate(d = new Date()) {
  const year = d.getFullYear();

  let month = d.getMonth() + 1;
  month = month < 10 ? `0${month}` : `${month}`;

  let day = d.getDate();
  day = day < 10 ? `0${day}` : `${day}`;

  let hours = d.getHours() + 1;
  hours = hours < 10 ? `0${hours}` : `${hours}`;

  let minutes = d.getMinutes() + 1;
  minutes = minutes < 10 ? `0${minutes}` : `${minutes}`;

  return `${year}-${month}-${day} ${hours}:${minutes}`;
}
